### ISSUE TITLE
java.lang.NoClassDefFoundError: java.time.OffsetDateTime

### ISSUE THREAD

**Issue by Melowetty** [Finnhub-Stock-API/finnhub-kotlin#5] opened 2021-03-13 18:58 UTC
Hello.
Every time when i call any method of library i get that error:
java.lang.ClassNotFoundException: java.time.OffsetDateTime

Can you help me with this problem please?

**Comment by nongdenchet** [comment] 2021-03-20 22:01
Hi @Melowetty, can you try with 1.2.0 and let me know?

**Comment by nongdenchet** [comment] 2021-05-06 23:08
closing due to no reply. Feel free to reopen if the issue is still happening

**Closed as completed by nongdenchet** 2021-05-06 23:08 UTC
